let token=localStorage.getItem('teb_admin_token')||'';let students=[],groups=[],courses=[],dialogMode=null,editId=null;let selectedCourse=localStorage.getItem('teb_admin_course')||'teb-ud1-ra1';const $=id=>document.getElementById(id);
async function req(path,opt={}){const h={'Content-Type':'application/json',...(opt.headers||{})};if(token)h.Authorization='Bearer '+token;const r=await fetch(path,{...opt,headers:h});if(opt.raw)return r;const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Error de comunicación');return d}
function loginMsg(t,bad=true){const e=$('loginMsg');e.textContent=t;e.className='notice '+(bad?'error':'')}
function cfg(){return courses.find(c=>c.id===selectedCourse)||courses[0]||{id:selectedCourse,unit:'UD1',ra:'RA1',title:''}}
function cp(s){return s.courses?.[selectedCourse]||{score:0,completion:0,timeSeconds:0,currentSession:1,status:'not-started',criteria:[],criterionFinals:{}}}
function ceList(){return selectedCourse==='teb-ud2-ra2'?['RA2.a','RA2.b','RA2.c','RA2.d','RA2.e','RA2.f','RA2.g','RA2.h','RA2.i']:['RA1.a','RA1.b','RA1.c','RA1.d','RA1.e','RA1.f','RA1.g']}
async function init(){if(token){try{await req('/api/me');return enter()}catch{token='';localStorage.removeItem('teb_admin_token')}}$('adminLogin').classList.remove('hidden')}
$('adminLoginBtn').onclick=async()=>{try{const d=await req('/api/login',{method:'POST',body:JSON.stringify({role:'admin',username:$('adminUser').value,password:$('adminPass').value})});token=d.token;localStorage.setItem('teb_admin_token',token);enter()}catch(e){loginMsg(e.message)}};
$('adminLogout').onclick=()=>{localStorage.removeItem('teb_admin_token');location.reload()};$('refreshBtn').onclick=loadAll;$('newStudent').onclick=()=>studentDialog();$('newGroup').onclick=()=>groupDialog();$('dialogCancel').onclick=closeDialog;$('eventsClose').onclick=()=>$('eventsDialog').classList.add('hidden');
$('courseSelect').onchange=()=>{selectedCourse=$('courseSelect').value;localStorage.setItem('teb_admin_course',selectedCourse);renderCourseControls();renderStudents();renderSummary()};
$('examToggle').onclick=async()=>{const c=cfg();if(c.id!=='teb-ud2-ra2')return;const enabled=!!c.examEnabled;const action=enabled?'desactivar':'activar';if(!confirm(`¿${action[0].toUpperCase()+action.slice(1)} el examen de la UD2 para el alumnado?`))return;try{const d=await req(`/api/admin/course-settings/${c.id}`,{method:'PUT',body:JSON.stringify({examEnabled:!enabled})});c.examEnabled=d.examEnabled?1:0;renderCourseControls()}catch(e){alert(e.message)}};
$('exportBtn').onclick=async()=>{const r=await fetch('/api/admin/export.csv?courseId='+encodeURIComponent(selectedCourse),{headers:{Authorization:'Bearer '+token}});if(!r.ok)return alert('No se pudo exportar.');const blob=await r.blob(),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`TEB_${cfg().unit}_seguimiento.csv`;a.click();URL.revokeObjectURL(a.href)};
async function enter(){$('adminLogin').classList.add('hidden');$('adminApp').classList.remove('hidden');await loadAll()}
async function loadAll(){try{const [g,s,c]=await Promise.all([req('/api/admin/groups'),req('/api/admin/students'),req('/api/courses')]);groups=g.groups||[];students=s.students||[];courses=c.courses||s.courses||[];if(!courses.some(x=>x.id===selectedCourse))selectedCourse=courses[0]?.id||'teb-ud1-ra1';renderCourseSelector();renderCourseControls();renderGroups();renderStudents();renderSummary()}catch(e){alert(e.message)}}
function renderCourseSelector(){$('courseSelect').innerHTML=courses.map(c=>`<option value="${escapeAttr(c.id)}" ${c.id===selectedCourse?'selected':''}>${escapeHtml(c.unit)} · ${escapeHtml(c.ra)}</option>`).join('')}
function renderCourseControls(){const c=cfg();$('courseLabel').textContent=`${c.unit} · ${c.title}`;$('examToggle').classList.toggle('hidden',c.id!=='teb-ud2-ra2');if(c.id==='teb-ud2-ra2'){$('examToggle').textContent=c.examEnabled?'Examen activado · Desactivar':'Examen bloqueado · Activar';$('examToggle').className='btn '+(c.examEnabled?'':'secondary')}}
function renderGroups(){$('groupsList').innerHTML=groups.length?groups.map(g=>`<div class="student-card"><div style="display:flex;justify-content:space-between;gap:8px"><span><strong>${escapeHtml(g.name)}</strong><br><span class="status ${g.active?'on':'off'}">${g.active?'Activo':'Inactivo'}</span></span><span><button class="mini edit" onclick="editGroup(${g.id})">Editar</button> <button class="mini delete" onclick="deleteGroup(${g.id})">Borrar</button></span></div></div>`).join(''):'<p class="muted">Todavía no hay grupos.</p>'}
function criterionBoxes(s){const p=cp(s), finals=p.criterionFinals||{}, cm=new Map((p.criteria||[]).map(c=>[c.criterion,c]));return ceList().map(ce=>{const f=finals[ce],legacy=cm.get(ce),score=Math.round(f?.score??legacy?.score??0),ok=f?!!f.passed:score>=50;let title=`${ce}: ${score}%`;if(selectedCourse==='teb-ud2-ra2'&&f)title+=` · Portafolio ${f.portfolio??'—'} · Examen ${f.exam??'—'}`;return `<span class="${ok?'ok':'bad'}" title="${escapeAttr(title)}">${ce.slice(-1)} ${score}</span>`}).join('')}
function renderStudents(){$('studentsBody').innerHTML=students.length?students.map(s=>{const p=cp(s),boxes=criterionBoxes(s);let state=p.status||'sin iniciar';if(selectedCourse==='teb-ud2-ra2'){const finals=Object.values(p.criterionFinals||{});if(finals.length&&finals.some(x=>!x.complete))state+=' · evaluación incompleta'}return `<tr><td><strong>${escapeHtml(s.lastName)}, ${escapeHtml(s.firstName)}</strong><br><small>${escapeHtml(s.code)}</small></td><td>${escapeHtml(s.groupName||'—')}</td><td><span class="status ${s.active?'on':'off'}">${s.active?'Activo':'Inactivo'}</span><br><small>${escapeHtml(state)}</small></td><td><strong>${Math.round(p.completion||0)}%</strong><br>Bloque ${p.currentSession||1}</td><td>${Math.round(p.score||0)}%</td><td>${((p.timeSeconds||0)/3600).toFixed(1)} h</td><td><div class="criteria-mini">${boxes}</div></td><td><button class="mini edit" onclick="editStudent(${s.id})">Editar</button> <button class="mini edit" onclick="resetPin(${s.id})">PIN</button> <button class="mini edit" onclick="showEvents(${s.id})">Actividad</button>${selectedCourse==='teb-ud2-ra2'?` <button class="mini edit" onclick="showRecovery(${s.id})">Recuperación</button>`:''} <button class="mini delete" onclick="deleteStudent(${s.id})">Borrar</button></td></tr>`}).join(''):'<tr><td colspan="8" class="muted">No hay alumnado registrado.</td></tr>'}
function renderSummary(){const total=students.length,started=students.filter(s=>(cp(s).completion||0)>0).length,finished=students.filter(s=>(cp(s).completion||0)>=100).length,avg=total?Math.round(students.reduce((a,s)=>a+(cp(s).completion||0),0)/total):0;let extra='';if(selectedCourse==='teb-ud2-ra2'){const c=cfg();extra=`<p>Examen: <strong>${c.examEnabled?'activado':'bloqueado'}</strong></p>`}$('summary').innerHTML=`<div class="metric-row"><div class="metric"><b>${total}</b><span class="muted">alumnos</span></div><div class="metric"><b>${started}</b><span class="muted">iniciados</span></div><div class="metric"><b>${finished}</b><span class="muted">completos</span></div></div><p>Progreso medio: <strong>${avg}%</strong></p>${extra}`}
function groupOptions(selected=''){return `<option value="">Sin grupo</option>`+groups.map(g=>`<option value="${g.id}" ${String(g.id)===String(selected)?'selected':''}>${escapeHtml(g.name)}</option>`).join('')}
function studentDialog(s=null){dialogMode=s?'edit-student':'new-student';editId=s?.id||null;$('dialogTitle').textContent=s?'Editar alumno':'Nuevo alumno';$('dialogBody').innerHTML=`<div class="row"><div class="field"><label>Nombre</label><input id="fName" value="${escapeAttr(s?.firstName||'')}"></div><div class="field"><label>Apellidos</label><input id="lName" value="${escapeAttr(s?.lastName||'')}"></div></div><div class="field"><label>Grupo</label><select id="groupId">${groupOptions(s?.groupId)}</select></div>${s?`<div class="field"><label><input id="active" type="checkbox" ${s.active?'checked':''}> Usuario activo</label></div>`:`<div class="field"><label>PIN temporal</label><input id="pin" value="1234" inputmode="numeric"><span class="muted">Por defecto: 1234</span></div>`}`;openDialog()}
function groupDialog(g=null){dialogMode=g?'edit-group':'new-group';editId=g?.id||null;$('dialogTitle').textContent=g?'Editar grupo':'Nuevo grupo';$('dialogBody').innerHTML=`<div class="field"><label>Nombre del grupo</label><input id="gName" value="${escapeAttr(g?.name||'')}"></div>${g?`<div class="field"><label><input id="gActive" type="checkbox" ${g.active?'checked':''}> Grupo activo</label></div>`:''}`;openDialog()}
function openDialog(){$('dialog').classList.remove('hidden')};function closeDialog(){$('dialog').classList.add('hidden');dialogMode=null;editId=null}
$('dialogSave').onclick=async()=>{try{if(dialogMode==='new-student'){const d=await req('/api/admin/students',{method:'POST',body:JSON.stringify({firstName:$('fName').value,lastName:$('lName').value,groupId:$('groupId').value||null,pin:$('pin').value||'1234'})});alert(`Alumno creado. Código: ${d.student.code} · PIN temporal: ${d.temporaryPin}`)}else if(dialogMode==='edit-student'){await req('/api/admin/students/'+editId,{method:'PUT',body:JSON.stringify({firstName:$('fName').value,lastName:$('lName').value,groupId:$('groupId').value||null,active:$('active').checked})})}else if(dialogMode==='new-group'){await req('/api/admin/groups',{method:'POST',body:JSON.stringify({name:$('gName').value})})}else if(dialogMode==='edit-group'){await req('/api/admin/groups/'+editId,{method:'PUT',body:JSON.stringify({name:$('gName').value,active:$('gActive').checked})})}closeDialog();await loadAll()}catch(e){alert(e.message)}};
window.editStudent=id=>studentDialog(students.find(x=>x.id===id));window.editGroup=id=>groupDialog(groups.find(x=>x.id===id));
window.deleteStudent=async id=>{const s=students.find(x=>x.id===id);if(!confirm(`¿Borrar definitivamente a ${s.firstName} ${s.lastName} y todo su progreso?`))return;try{await req('/api/admin/students/'+id,{method:'DELETE'});await loadAll()}catch(e){alert(e.message)}};
window.deleteGroup=async id=>{const g=groups.find(x=>x.id===id);if(!confirm(`¿Borrar el grupo ${g.name}? Los alumnos quedarán sin grupo.`))return;try{await req('/api/admin/groups/'+id,{method:'DELETE'});await loadAll()}catch(e){alert(e.message)}};
window.resetPin=async id=>{const pin=prompt('Nuevo PIN temporal (4-8 cifras):','1234');if(pin===null)return;try{const d=await req(`/api/admin/students/${id}/reset-pin`,{method:'POST',body:JSON.stringify({pin})});alert('PIN actualizado: '+d.temporaryPin)}catch(e){alert(e.message)}};
window.showEvents=async id=>{const s=students.find(x=>x.id===id);$('eventsTitle').textContent=`Actividad · ${s.firstName} ${s.lastName} · ${cfg().unit}`;$('eventsList').innerHTML='<p>Cargando…</p>';$('eventsDialog').classList.remove('hidden');try{const d=await req(`/api/admin/students/${id}/events?courseId=${encodeURIComponent(selectedCourse)}`);$('eventsList').innerHTML=d.events.length?d.events.map(e=>`<div class="event"><strong>${escapeHtml(e.eventType)}</strong> · ${escapeHtml(e.ref||'')} ${e.criterion?`<span class="chip">${escapeHtml(e.criterion)}</span>`:''} ${e.score!=null?`<b>${Math.round(e.score)}%</b>`:''}<br><small>${new Date(e.createdAt).toLocaleString('es-ES')}</small></div>`).join(''):'<p class="muted">No hay actividad registrada.</p>'}catch(e){$('eventsList').textContent=e.message}};
window.showRecovery=async id=>{const s=students.find(x=>x.id===id);$('eventsTitle').textContent=`Plan de recuperación · ${s.firstName} ${s.lastName}`;$('eventsList').innerHTML='<p>Cargando…</p>';$('eventsDialog').classList.remove('hidden');try{const d=await req(`/api/admin/students/${id}/recovery?courseId=${encodeURIComponent(selectedCourse)}`);if(!d.pending.length){$('eventsList').innerHTML='<div class="notice"><strong>No hay criterios pendientes.</strong></div>';return}$('eventsList').innerHTML=`<p>${d.passed}/${d.total} criterios superados. La recuperación se limita a los criterios pendientes.</p>`+d.pending.map(x=>`<div class="event"><strong>${x.criterion} · ${x.currentScore.toFixed(1)}%</strong><br>${escapeHtml(x.objective)}<br><small>Propuesta: ${x.proposal.microactivities} actividades nuevas + prueba de dominio de ${x.proposal.masteryCheck} ítems${x.proposal.caseRequired?' + caso práctico específico':''}.</small>${x.diagnostics.length?`<br><small>Errores detectados: ${x.diagnostics.map(escapeHtml).join(' · ')}</small>`:''}</div>`).join('')}catch(e){$('eventsList').textContent=e.message}};
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function escapeAttr(v){return escapeHtml(v)}init();
