let token=localStorage.getItem('teb_admin_token')||'';let students=[],groups=[],dialogMode=null,editId=null;const $=id=>document.getElementById(id);
async function req(path,opt={}){const h={'Content-Type':'application/json',...(opt.headers||{})};if(token)h.Authorization='Bearer '+token;const r=await fetch(path,{...opt,headers:h});if(opt.raw)return r;const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Error de comunicación');return d}
function loginMsg(t,bad=true){const e=$('loginMsg');e.textContent=t;e.className='notice '+(bad?'error':'')}
async function init(){if(token){try{await req('/api/me');return enter()}catch{token='';localStorage.removeItem('teb_admin_token')}}$('adminLogin').classList.remove('hidden')}
$('adminLoginBtn').onclick=async()=>{try{const d=await req('/api/login',{method:'POST',body:JSON.stringify({role:'admin',username:$('adminUser').value,password:$('adminPass').value})});token=d.token;localStorage.setItem('teb_admin_token',token);enter()}catch(e){loginMsg(e.message)}};
$('adminLogout').onclick=()=>{localStorage.removeItem('teb_admin_token');location.reload()};$('refreshBtn').onclick=loadAll;$('newStudent').onclick=()=>studentDialog();$('newGroup').onclick=()=>groupDialog();$('dialogCancel').onclick=closeDialog;$('eventsClose').onclick=()=>$('eventsDialog').classList.add('hidden');
$('exportBtn').onclick=async()=>{const r=await fetch('/api/admin/export.csv',{headers:{Authorization:'Bearer '+token}});if(!r.ok)return alert('No se pudo exportar.');const blob=await r.blob(),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='TEB_UD1_seguimiento.csv';a.click();URL.revokeObjectURL(a.href)};
async function enter(){$('adminLogin').classList.add('hidden');$('adminApp').classList.remove('hidden');await loadAll()}
async function loadAll(){try{const [g,s]=await Promise.all([req('/api/admin/groups'),req('/api/admin/students')]);groups=g.groups||[];students=s.students||[];renderGroups();renderStudents();renderSummary()}catch(e){alert(e.message)}}
function renderGroups(){$('groupsList').innerHTML=groups.length?groups.map(g=>`<div class="student-card"><div style="display:flex;justify-content:space-between;gap:8px"><span><strong>${escapeHtml(g.name)}</strong><br><span class="status ${g.active?'on':'off'}">${g.active?'Activo':'Inactivo'}</span></span><span><button class="mini edit" onclick="editGroup(${g.id})">Editar</button> <button class="mini delete" onclick="deleteGroup(${g.id})">Borrar</button></span></div></div>`).join(''):'<p class="muted">Todavía no hay grupos.</p>'}
function renderStudents(){$('studentsBody').innerHTML=students.length?students.map(s=>{const cm=new Map((s.criteria||[]).map(c=>[c.criterion,c]));const boxes=['RA1.a','RA1.b','RA1.c','RA1.d','RA1.e','RA1.f','RA1.g'].map(ce=>{const c=cm.get(ce),sc=Math.round(c?.score||0);return `<span class="${sc>=70?'ok':'bad'}" title="${ce}: ${sc}%">${ce.slice(-1)} ${sc}</span>`}).join('');return `<tr><td><strong>${escapeHtml(s.lastName)}, ${escapeHtml(s.firstName)}</strong><br><small>${escapeHtml(s.code)}</small></td><td>${escapeHtml(s.groupName||'—')}</td><td><span class="status ${s.active?'on':'off'}">${s.active?'Activo':'Inactivo'}</span><br><small>${escapeHtml(s.status||'sin iniciar')}</small></td><td><strong>${Math.round(s.completion||0)}%</strong><br>Bloque ${s.currentSession||1}</td><td>${Math.round(s.score||0)}%</td><td>${((s.timeSeconds||0)/3600).toFixed(1)} h</td><td><div class="criteria-mini">${boxes}</div></td><td><button class="mini edit" onclick="editStudent(${s.id})">Editar</button> <button class="mini edit" onclick="resetPin(${s.id})">PIN</button> <button class="mini edit" onclick="showEvents(${s.id})">Actividad</button> <button class="mini delete" onclick="deleteStudent(${s.id})">Borrar</button></td></tr>`}).join(''):'<tr><td colspan="8" class="muted">No hay alumnado registrado.</td></tr>'}
function renderSummary(){const total=students.length,started=students.filter(s=>(s.completion||0)>0).length,finished=students.filter(s=>(s.completion||0)>=100).length,avg=total?Math.round(students.reduce((a,s)=>a+(s.completion||0),0)/total):0;$('summary').innerHTML=`<div class="metric-row"><div class="metric"><b>${total}</b><span class="muted">alumnos</span></div><div class="metric"><b>${started}</b><span class="muted">iniciados</span></div><div class="metric"><b>${finished}</b><span class="muted">completos</span></div></div><p>Progreso medio: <strong>${avg}%</strong></p>`}
function groupOptions(selected=''){return `<option value="">Sin grupo</option>`+groups.map(g=>`<option value="${g.id}" ${String(g.id)===String(selected)?'selected':''}>${escapeHtml(g.name)}</option>`).join('')}
function studentDialog(s=null){dialogMode=s?'edit-student':'new-student';editId=s?.id||null;$('dialogTitle').textContent=s?'Editar alumno':'Nuevo alumno';$('dialogBody').innerHTML=`<div class="row"><div class="field"><label>Nombre</label><input id="fName" value="${escapeAttr(s?.firstName||'')}"></div><div class="field"><label>Apellidos</label><input id="lName" value="${escapeAttr(s?.lastName||'')}"></div></div><div class="field"><label>Grupo</label><select id="groupId">${groupOptions(s?.groupId)}</select></div>${s?`<div class="field"><label><input id="active" type="checkbox" ${s.active?'checked':''}> Usuario activo</label></div>`:`<div class="field"><label>PIN temporal</label><input id="pin" value="1234" inputmode="numeric"><span class="muted">Por defecto: 1234</span></div>`}`;openDialog()}
function groupDialog(g=null){dialogMode=g?'edit-group':'new-group';editId=g?.id||null;$('dialogTitle').textContent=g?'Editar grupo':'Nuevo grupo';$('dialogBody').innerHTML=`<div class="field"><label>Nombre del grupo</label><input id="gName" value="${escapeAttr(g?.name||'')}"></div>${g?`<div class="field"><label><input id="gActive" type="checkbox" ${g.active?'checked':''}> Grupo activo</label></div>`:''}`;openDialog()}
function openDialog(){$('dialog').classList.remove('hidden')};function closeDialog(){$('dialog').classList.add('hidden');dialogMode=null;editId=null}
$('dialogSave').onclick=async()=>{try{if(dialogMode==='new-student'){const d=await req('/api/admin/students',{method:'POST',body:JSON.stringify({firstName:$('fName').value,lastName:$('lName').value,groupId:$('groupId').value||null,pin:$('pin').value||'1234'})});alert(`Alumno creado. Código: ${d.student.code} · PIN temporal: ${d.temporaryPin}`)}else if(dialogMode==='edit-student'){await req('/api/admin/students/'+editId,{method:'PUT',body:JSON.stringify({firstName:$('fName').value,lastName:$('lName').value,groupId:$('groupId').value||null,active:$('active').checked})})}else if(dialogMode==='new-group'){await req('/api/admin/groups',{method:'POST',body:JSON.stringify({name:$('gName').value})})}else if(dialogMode==='edit-group'){await req('/api/admin/groups/'+editId,{method:'PUT',body:JSON.stringify({name:$('gName').value,active:$('gActive').checked})})}closeDialog();await loadAll()}catch(e){alert(e.message)}};
window.editStudent=id=>studentDialog(students.find(x=>x.id===id));window.editGroup=id=>groupDialog(groups.find(x=>x.id===id));
window.deleteStudent=async id=>{const s=students.find(x=>x.id===id);if(!confirm(`¿Borrar definitivamente a ${s.firstName} ${s.lastName} y todo su progreso?`))return;try{await req('/api/admin/students/'+id,{method:'DELETE'});await loadAll()}catch(e){alert(e.message)}};
window.deleteGroup=async id=>{const g=groups.find(x=>x.id===id);if(!confirm(`¿Borrar el grupo ${g.name}? Los alumnos quedarán sin grupo.`))return;try{await req('/api/admin/groups/'+id,{method:'DELETE'});await loadAll()}catch(e){alert(e.message)}};
window.resetPin=async id=>{const pin=prompt('Nuevo PIN temporal (4-8 cifras):','1234');if(pin===null)return;try{const d=await req(`/api/admin/students/${id}/reset-pin`,{method:'POST',body:JSON.stringify({pin})});alert('PIN actualizado: '+d.temporaryPin)}catch(e){alert(e.message)}};
window.showEvents=async id=>{const s=students.find(x=>x.id===id);$('eventsTitle').textContent=`Actividad · ${s.firstName} ${s.lastName}`;$('eventsList').innerHTML='<p>Cargando…</p>';$('eventsDialog').classList.remove('hidden');try{const d=await req(`/api/admin/students/${id}/events`);$('eventsList').innerHTML=d.events.length?d.events.map(e=>`<div class="event"><strong>${escapeHtml(e.eventType)}</strong> · ${escapeHtml(e.ref||'')} ${e.criterion?`<span class="chip">${escapeHtml(e.criterion)}</span>`:''} ${e.score!=null?`<b>${Math.round(e.score)}%</b>`:''}<br><small>${new Date(e.createdAt).toLocaleString('es-ES')}</small></div>`).join(''):'<p class="muted">No hay actividad registrada.</p>'}catch(e){$('eventsList').textContent=e.message}};
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function escapeAttr(v){return escapeHtml(v)}init();
