(()=>{
  const C=window.TEB_UD2,$=id=>document.getElementById(id),COURSE_ID='teb-ud2-ra2';
  if(!C?.examBank)throw new Error('No se ha cargado el banco de examen UD2');
  const quota={'RA2.a':10,'RA2.b':10,'RA2.c':13,'RA2.d':12,'RA2.e':10,'RA2.f':10,'RA2.g':10,'RA2.h':10,'RA2.i':15};
  let token=localStorage.getItem('teb_student_token')||'',profile=null,progress=null,selected=[],state={ids:[],index:0,answers:Array(100).fill(null),started:false,submitted:false,startedAt:null,submittedAt:null,result:null};
  async function req(path,opt={}){const h={'Content-Type':'application/json',...(opt.headers||{})};if(token)h.Authorization='Bearer '+token;const r=await fetch(path,{...opt,headers:h});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Error de comunicación');return d}
  function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
  function rng(seed){return()=>((seed=Math.imul(seed,1664525)+1013904223>>>0)/4294967296)}
  function pick100(studentCode){const r=rng(hash(studentCode+'|UD2|EXAM|v2')),out=[];for(const [ce,n] of Object.entries(quota)){let p=C.examBank.filter(x=>x.criterion===ce).slice();for(let i=p.length-1;i>0;i--){let j=Math.floor(r()*(i+1));[p[i],p[j]]=[p[j],p[i]]}out.push(...p.slice(0,n))}for(let i=out.length-1;i>0;i--){let j=Math.floor(r()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out}
  async function save(){progress.state={...(progress.state||{}),examState:state};await req('/api/progress',{method:'PUT',body:JSON.stringify({courseId:COURSE_ID,version:'0.2.0',state:progress.state,score:progress.score||0,completion:progress.completion||0,timeSeconds:progress.timeSeconds||0,currentSession:progress.currentSession||1,status:progress.status||'incomplete'})})}
  function score(){let correct=0,wrong=0,blank=0;const by={};Object.keys(C.criteria).forEach(ce=>by[ce]={c:0,w:0,b:0,n:0});selected.forEach((q,i)=>{const a=state.answers[i],x=by[q.criterion];x.n++;if(a==null){blank++;x.b++}else if(Number(a)===q.answerIndex){correct++;x.c++}else{wrong++;x.w++}});const points=Math.max(0,correct-.5*wrong);const criteria={};for(const [ce,x] of Object.entries(by))criteria[ce]=Math.max(0,Math.round(((x.c-.5*x.w)/x.n*100)*100)/100);return{correct,wrong,blank,points,raw:Math.round(points*100)/100,criteria}}
  function renderQuestion(){if(state.submitted){renderResult();return}const q=selected[state.index];$('examCard').classList.remove('hidden');$('bar').style.width=`${state.index+1}%`;$('counter').textContent=`Pregunta ${state.index+1} / 100 · ${q.criterion}`;$('question').innerHTML=`<span class="chip">${q.criterion}</span><h2>${q.prompt}</h2>${q.choices.map((o,i)=>`<label class="option"><input type="radio" name="ans" value="${i}" ${state.answers[state.index]===i?'checked':''}> ${o}</label>`).join('')}`;document.querySelectorAll('input[name=ans]').forEach(x=>x.onchange=async()=>{state.answers[state.index]=Number(x.value);await save()});$('prevBtn').disabled=state.index===0;$('nextBtn').disabled=state.index===99}
  function renderResult(){const r=state.result||score();$('examCard').classList.add('hidden');$('resultCard').classList.remove('hidden');$('summary').innerHTML=`<p><strong>Aciertos:</strong> ${r.correct} · <strong>Errores:</strong> ${r.wrong} · <strong>En blanco:</strong> ${r.blank}</p><p><strong>Puntuación:</strong> ${r.raw.toFixed(2)} / 100</p><p class="muted">Fórmula: aciertos − 0,5 × errores.</p>`;$('criteria').innerHTML=Object.entries(C.criteria).map(([ce,x])=>`<div class="criterion"><strong>${ce}</strong><p>${x.label}</p><b>${Number(r.criteria[ce]||0).toFixed(1)}%</b></div>`).join('')}
  async function start(){if(state.submitted)return renderResult();state.started=true;state.startedAt=state.startedAt||new Date().toISOString();$('availability').innerHTML='<div class="good" style="padding:12px;border-radius:8px">Examen iniciado. Puedes desplazarte entre preguntas antes de entregar.</div>';$('examCard').classList.remove('hidden');await save();renderQuestion()}
  async function submit(){if(state.submitted)return;if(!confirm('¿Entregar definitivamente el examen? No podrás modificar ninguna respuesta después.'))return;const r=score();try{await req('/api/assessment',{method:'POST',body:JSON.stringify({courseId:COURSE_ID,instrument:'exam',criteria:r.criteria,ref:'ud2-exam-teb',payload:{questions:100,correct:r.correct,wrong:r.wrong,blank:r.blank,penalty:-0.5,score:r.raw}})});state.submitted=true;state.submittedAt=new Date().toISOString();state.result=r;await save();window.parent.postMessage({type:'ud2-exam-submitted',result:r},'*');renderResult()}catch(e){alert(e.message)}}
  function report(){const r=state.result||score();const html=`<!doctype html><meta charset="utf-8"><h1>TEB · UD2 · Informe de examen</h1><p>Alumno: ${profile.firstName} ${profile.lastName}</p><p>Aciertos: ${r.correct} · Errores: ${r.wrong} · En blanco: ${r.blank}</p><p>Penalización: 1 error = -0,5 aciertos</p><p><strong>Nota: ${r.raw.toFixed(2)} / 100</strong></p><table border="1" cellpadding="6"><tr><th>Criterio</th><th>Resultado</th></tr>${Object.keys(C.criteria).map(ce=>`<tr><td>${ce}</td><td>${Number(r.criteria[ce]||0).toFixed(2)}%</td></tr>`).join('')}</table>`;const b=new Blob([html],{type:'text/html'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='TEB_UD2_examen_informe.html';a.click();URL.revokeObjectURL(a.href)}
  async function init(){if(!token){$('availability').innerHTML='<div class="bad" style="padding:12px;border-radius:8px">Debes iniciar sesión en TEB antes de abrir el examen.</div>';return}profile=(await req('/api/me')).profile;progress=await req('/api/progress?courseId='+encodeURIComponent(COURSE_ID));const server=progress.state?.examState;if(server)state={...state,...server,answers:Array.isArray(server.answers)&&server.answers.length===100?server.answers:Array(100).fill(null)};selected=pick100(profile.code);if(!Array.isArray(state.ids)||state.ids.length!==100)state.ids=selected.map(x=>x.id);selected=state.ids.map(id=>C.examBank.find(x=>x.id===id)).filter(Boolean);if(selected.length!==100){selected=pick100(profile.code);state.ids=selected.map(x=>x.id)}if(state.submitted){$('availability').innerHTML='<div class="good" style="padding:12px;border-radius:8px">Examen ya entregado.</div>';renderResult();return}const settings=await req('/api/course-settings?courseId='+encodeURIComponent(COURSE_ID));if(!settings.examEnabled){$('availability').innerHTML='<div class="locked" style="padding:12px;border-radius:8px"><strong>Examen bloqueado.</strong><br>El profesor todavía no ha activado esta prueba.</div>';return}$('availability').innerHTML=`<div class="good" style="padding:12px;border-radius:8px"><strong>Examen disponible.</strong><br>${state.started?'Tienes un intento abierto. Puedes continuar donde lo dejaste.':'Cuando pulses comenzar se abrirá tu único intento.'}</div><button id="startBtn" class="btn" style="margin-top:12px">${state.started?'Continuar examen':'Comenzar examen'}</button>`;$('startBtn').onclick=start;if(state.started)renderQuestion()}
  $('prevBtn').onclick=async()=>{if(state.index>0){state.index--;await save();renderQuestion()}};$('nextBtn').onclick=async()=>{if(state.index<99){state.index++;await save();renderQuestion()}};$('submitBtn').onclick=submit;$('reportBtn').onclick=report;
  init().catch(e=>$('availability').innerHTML=`<div class="bad" style="padding:12px;border-radius:8px">${e.message}</div>`);
})();
