(()=>{
  const COURSE_ID='teb-ud2-ra2',STORE='teb_ud2_sim_state_v1',$=id=>document.getElementById(id);
  const RA2_WEIGHTS={'RA2.a':.10,'RA2.b':.10,'RA2.c':.125,'RA2.d':.125,'RA2.e':.10,'RA2.f':.10,'RA2.g':.10,'RA2.h':.10,'RA2.i':.15};
  let token=localStorage.getItem('teb_student_token')||'',profile=null,progress=null,lastTick=Date.now(),timer=null,saving=false,currentMode='simulator';
  async function req(path,opt={}){const headers={'Content-Type':'application/json',...(opt.headers||{})};if(token)headers.Authorization='Bearer '+token;const r=await fetch(path,{...opt,headers});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Error de comunicación');return d}
  function msg(text,bad=false){$('loginMsg').textContent=text;$('loginMsg').className='notice '+(bad?'error':'')}
  function simState(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch{return{}}}
  function phaseMetrics(){const s=simState(),server=progress?.state||{};const simPct=Math.min(1,(s.completedScenarios||[]).length/14);const p=server.portfolioState||{},pPct=p.submitted?1:Math.min(1,Object.keys(p.scores||{}).length/100);const e=server.examState||{},answered=Array.isArray(e.answers)?e.answers.filter(x=>x!=null).length:0,ePct=e.submitted?1:(e.started?answered/100:0);return{completion:Math.round((simPct*.50+pPct*.30+ePct*.20)*100),simPct,pPct,ePct}}
  function aggregateScore(){const f=progress?.criterionFinals||{};return Math.round(Object.entries(RA2_WEIGHTS).reduce((a,[ce,w])=>a+(Number(f[ce]?.score)||0)*w,0)*100)/100}
  function aggregateStatus(){const f=Object.values(progress?.criterionFinals||{}),complete=f.length===9&&f.every(x=>x.complete);if(!complete)return phaseMetrics().completion?'incomplete':'not-started';const passed=f.filter(x=>x.passed).length,overall=aggregateScore();return overall>=50&&passed>=8?'passed':'failed'}
  async function refreshProgress(){progress=await req('/api/progress?courseId='+encodeURIComponent(COURSE_ID));if(progress.state?.simulatorState)localStorage.setItem(STORE,JSON.stringify(progress.state.simulatorState));updateHeader()}
  async function persistAggregate(){if(!progress)return;const m=phaseMetrics(),score=aggregateScore(),status=aggregateStatus();await req('/api/progress',{method:'PUT',body:JSON.stringify({courseId:COURSE_ID,version:'0.2.0',state:progress.state||{},score,completion:m.completion,timeSeconds:Math.round(progress.timeSeconds||0),currentSession:Math.max(1,Math.min(20,Math.ceil(m.completion/5)||1)),status})});progress.score=score;progress.completion=m.completion;progress.status=status;updateHeader()}
  async function load(){if(!token){$('loginBox').classList.remove('hidden');return}try{profile=(await req('/api/me')).profile;await refreshProgress();$('studentName').textContent=`${profile.firstName} ${profile.lastName} · ${profile.code}`;$('loginBox').classList.add('hidden');$('hostApp').classList.remove('hidden');openPage('ud2-simulator.html','simulator',false);lastTick=Date.now();clearInterval(timer);timer=setInterval(()=>{if(currentMode==='simulator')sync()},15000)}catch(e){localStorage.removeItem('teb_student_token');token='';$('loginBox').classList.remove('hidden');msg(e.message,true)}}
  async function sync(){if(!token||saving)return;saving=true;try{const now=Date.now(),elapsed=Math.max(0,(now-lastTick)/1000);lastTick=now;const s=simState();progress=progress||{state:{},timeSeconds:0};progress.timeSeconds=(Number(progress.timeSeconds)||0)+elapsed;progress.state={...(progress.state||{}),simulatorState:s};const m=phaseMetrics();$('saveState').textContent='Guardando…';await req('/api/progress',{method:'PUT',body:JSON.stringify({courseId:COURSE_ID,version:'0.2.0',state:progress.state,score:aggregateScore(),completion:m.completion,timeSeconds:Math.round(progress.timeSeconds),currentSession:Math.max(1,Math.min(20,Math.ceil(m.completion/5)||1)),status:aggregateStatus()})});progress.completion=m.completion;$('saveState').textContent='Guardado';updateHeader()}catch(e){$('saveState').textContent='Sin guardar';console.error(e)}finally{saving=false}}
  function updateHeader(){const m=phaseMetrics();$('progressText').textContent=`${m.completion} % · nota ${aggregateScore().toFixed(1)}`}
  async function recordScenario(d){try{for(const ce of d.criteria||[])await req('/api/events',{method:'POST',body:JSON.stringify({courseId:COURSE_ID,eventType:d.formative?'ud2-formative-case':'ud2-evaluable-case',ref:d.ref,criterion:ce,score:d.score,payload:{stage:d.stage,formative:!!d.formative,errorType:d.errorType||''}})});await sync()}catch(e){console.error(e)}}
  async function openPage(page,mode,saveBefore=true){if(saveBefore&&currentMode==='simulator')await sync();currentMode=mode;document.querySelectorAll('.ud2nav button').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('ud2Frame').src=page;lastTick=Date.now()}
  document.querySelectorAll('.ud2nav button').forEach(b=>b.onclick=()=>openPage(b.dataset.page,b.dataset.mode));
  window.addEventListener('message',async e=>{const d=e.data;if(!d)return;if(d.type==='teb-activity-result')return recordScenario(d);if(d.type==='ud2-portfolio-submitted'||d.type==='ud2-exam-submitted'){try{await refreshProgress();await persistAggregate()}catch(err){console.error(err)}}});
  $('loginBtn').onclick=async()=>{try{const d=await req('/api/login',{method:'POST',body:JSON.stringify({role:'student',code:$('studentCode').value,pin:$('studentPin').value})});token=d.token;profile=d.profile;localStorage.setItem('teb_student_token',token);await load()}catch(e){msg(e.message,true)}};
  $('logoutBtn').onclick=async()=>{if(currentMode==='simulator')await sync();localStorage.removeItem('teb_student_token');location.reload()};
  window.addEventListener('beforeunload',()=>{if(currentMode==='simulator'){try{sync()}catch{}}});
  load();
})();
